eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
         preferIpAddress: true
spring:
   application:
      name: domainMS
server:
   port: 8081